language: node_js
node_js:
  - '12'
  - '11'
  - '10'
cache: yarn
script:
  - (cd packages/catalyst && yarn tsc --noEmit)
  - (cd packages/catalyst-client && yarn tsc --noEmit)
  - (cd packages/catalyst && yarn test)
  - (cd packages/catalyst-client && yarn test)
