#!/usr/bin/env bash

set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$1" != "--force" ]; then
  if [[ "$current_branch" != "master" ]]; then
    echo "Prepack command may only be run from master."
    exit 1
  fi

  if [[ $(git status --porcelain --untracked-files=no -- | wc -l | tr -d " ") != '0' ]]  ; then
    echo "Please commit, discard, or stash the following changes and try again:"
    git status --porcelain
    exit 1
  fi
fi

rm -rf lib

yarn test

webpack --config=webpack.config.js --bail

cp src/index.js lib/index.js

for src_path in src/*
do
  lib_path=`echo $src_path | awk 'gsub("src", "lib")'`

  if [ $lib_path != "lib/dev-client" ]; then
    cp -R $src_path $lib_path
  fi
done
