name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-14-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install

      - name: Run Prettier Check
        run: yarn prettier:check

      - name: Run ESLint
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node Dependencies
        run: yarn install

      - name: Run Tests (catalyst)
        run: yarn test
        working-directory: ./packages/catalyst

      - name: Run Tests (catalyst-client)
        run: yarn test
        working-directory: ./packages/catalyst-client
